### ISSUE TITLE
Make the current API follow REST protocol

### ISSUE THREAD

**Issue by rushitote** [rushitote/chat-app#21]

**Comment by TheTrio** [comment]
Listing out all the routes presently available 

1. `POST /login` 
2. `POST /logout`
3. `POST /create`
4. `GET /authenticated`
5. `POST /rooms/create`
6. `GET /rooms/get`
7. `POST /rooms/add`
8. `POST /rooms/remove`
9. `POST /messages/get`
10. `GET /messages/get`

Here's what I'm thinking

1. `/create` should probably be `/register`
2. For deleting stuff, we should use the [DELETE](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE) HTTP method. For example, `POST /rooms/remove` should become `DELETE /rooms`
3. All the `rooms` routes could be simplified to just `/rooms`. Same for `/messages`

I'm also starting to think that the `/authenticated` route is unnecessary. The rest of the routes(afaik) return a `401` anyway in the case the user is not logged in. 

What do you think?

**Comment by rushitote** [comment]
Yeah, that seems a great way to start with this! Also, actually I made a mistake in naming the mapping with rooms, so the current `POST /rooms/remove` could become `DELETE /mapping` as you said. I will fix this soon.

My major focus was on the stateless principle of REST, which we don't follow since we use sessions on the server side. So we need to change the auth system a bit.
