### ISSUE TITLE
Make repository production ready

### ISSUE THREAD

**Issue by TheTrio** [rushitote/chat-app#30]
For now, I believe its best to deploy on Heroku because of its ease of use. 

To do that, we must make several(breaking) changes. 

1. Reset all `CORS` configuration from both the front end and back-end.
2. Group the back-end routes under `/api` 
3. Replace all references to `localhost` in the front-end to just `/api`
4. Configure a proxy to make running this in development mode a bit easier. The Create React App docs have a page detailing on just this - see [Proxying API Requests in Development](https://create-react-app.dev/docs/proxying-api-requests-in-development/)
5. Use environment variables for storing the database information instead of a config file (which is hard to use in production)
6. Stop using the MemoryStore. Instead use something like MongoStore for storing sessions in production
7. Add Heroku specific configuration to ensure automatic building of both react  and the typescript express app.  

And that's all I can think of currently. I should be able to merge a PR for this soon, provided we agree on all of the above points. 

What do you think?

**Comment by rushitote** [comment]
Here is what I think:

1. I was able to deploy the server on Azure VM with the frontend on Vercel with SSL and CORS working fine (https://chat-app-pink-xi.vercel.app/). And that barely required a small change in session configuration and a new environment variable for socket URL in frontend. So, I think this way Vercel deploys automatically on every push and we can easily write an Actions script to initiate a `git pull` and then a `pm2 restart` in the server at every push. This will require addition of just one script and will not require any breaking changes.
2. Yep, we will have to do this in any case.
3. There is already a `REACT_APP_HOST` env variable, where we can add the backend server URL.
4. I am not sure how convenient would that be.
5. Yep, right we need to do this.
6. Yeah, we can use either Mongo or Redis here.

Would this be better?

**Comment by TheTrio** [comment]
I thinlk #32 resolves this. Great work!
